Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.]
  InstanceImageIdParameter:
    Type: String
    Default: ami-036c2987dfef867fb
    AllowedValues:
      - ami-076cbd561ae9c19e9
      - ami-036c2987dfef867fb
    Description: Enter ami-036c2987dfef867fb or ami-036c2987dfef867fb. Default is tami-036c2987dfef867fb
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-036c2987dfef867fb
      InstanceType: 
        Ref: InstanceTypeParameter
      UserData: !Base64 
        'Fn::Sub': >
          #!/bin/bash -xe

          # Install Apache web server

          yum update -y

          yum install -y httpd

          systemctl start httpd

          systemctl enable httpd

          echo "<html><body><h1>Hello World!</h1></body></html>" >
          /var/www/html/index.html
