AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample loadbalancer and ASG
Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String
  InstanceType:
    Type: String
  AvailabilityZones:
    Type: List

Resources:    
  # security group
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: 
          Fn::GetAtt:
          - ELBSecurityGroup
          - GroupId
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  CFLoadBalancer:
      Type: AWS::ElasticLoadBalancing::LoadBalancer
      Properties:
        Listeners:
          - LoadBalancerPort: '80'
            InstancePort: '80'
            Protocol: HTTP
        AvailabilityZones: 
        SecurityGroups: [!Ref ELBSecurityGroup]

  CFAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !Ref AvailabilityZones
      LaunchConfigurationName: !Ref CFLaunchConfiguration
      MinSize: '2'
      MaxSize: '5'
      LoadBalancerNames: [!Ref CFLoadBalancer]

  CFLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: 'ami-12345678'
      InstanceType: !Ref InstanceType
      SecurityGroups: [!Ref EC2SecurityGroup]
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Hello World from $(hostname -f) </h1></body></html>" >
          /var/www/html/index.html
