version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U demo -d demo'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s 

  init-db:
    environment:
      DB_NAME: demo
      DB_USER: demo
      DB_PASS: demo
      DB_HOST: db
      DB_PORT: 5432
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    command: python db_init.py
  worker:
    build: ./app
    depends_on:
      - db
    environment:
      SQS_QUEUE_URL:
      ACCESS_KEY:
      SECRET_KEY:
      DB_NAME: demo
      DB_USER: demo
      DB_PASS: demo
      DB_HOST: db
      DB_PORT: 5432
    command: python worker.py
  api:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQS_QUEUE_URL:
      ACCESS_KEY:
      SECRET_KEY:
      DB_NAME: demo
      DB_USER: demo
      DB_PASS: demo
      DB_HOST: db
      DB_PORT: 5432
